apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-runner.fullname" . }}
  labels:
{{ include "github-runner.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.gitHubRunner.secret}}
  {{$key}}: {{$value| b64enc | quote}}
  {{- end}}
