{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "github-runner.serviceAccountName" . }}
  labels:
{{ include "github-runner.labels" . | indent 4 }}
{{- end -}}
